<?php

namespace AppBundle\Repository;

/**
 * ContenuConteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuConteRepository extends \Doctrine\ORM\EntityRepository
{
}
